language: ruby
cache: bundler
rvm:
  - 2.6.6
  - 2.7.2
before_install: gem install bundler -v 2.2.0
notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always
