language: ruby
cache: bundler
rvm:
  - 2.3.7
  - 2.4.5
  - 2.5.3
  - 2.6.1
before_install: gem install bundler -v 2.0.1
notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always
